baseUrl: "https://www.deadgray.com/"
#baseUrl: "http://localhost:3000/"
locale: "en-US"
title: "Dead Gray"
description: "Description for my site"
navigation:
    - label: "About"
      url: "/about/"
footer-socials:
  - title: "Instagram"
    url: "https://www.instagram.com/deadgrayband/"
  - title: "Facebook"
    url: "https://www.facebook.com/deadgraybandofficial/"
  - title: "YouTube"
    url: "https://www.youtube.com/@DeadGrayBand/"
  - title: "TikTok"
    url: "https://www.tiktok.com/@dead.gray.band/"
